const courses = [
  {
    name: "React - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "JavaScript", "Library"],
    isPublished: true,
    price: 30.99,
  },
  {
    name: "Node.js - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Backend", "JavaScript", "Runtime"],
    isPublished: true,
    price: 15.0,
  },
  {
    name: "Angular - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: false,
    price: 20.0,
  },
  {
    name: "MongoDB - The Complete Developer's Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Database", "NoSQL"],
    isPublished: true,
    price: 10.0,
  },
  {
    name: "JavaScript - Advanced Concepts",
    author: "Jonas Schmedtmann",
    tags: ["Frontend", "JavaScript", "Advanced"],
    isPublished: true,
    price: 25.99,
  },
  {
    name: "Python - The Complete Guide",
    author: "Jose Portilla",
    tags: ["Backend", "Python", "Programming"],
    isPublished: true,
    price: 22.5,
  },
  {
    name: "Vue.js - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: true,
    price: 18.99,
  },
  {
    name: "SQL - The Complete Developer's Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Database", "SQL"],
    isPublished: true,
    price: 12.99,
  },
  {
    name: "TypeScript - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "JavaScript", "TypeScript"],
    isPublished: false,
    price: 19.99,
  },
  {
    name: "Django - The Complete Guide",
    author: "Jose Portilla",
    tags: ["Backend", "Python", "Framework"],
    isPublished: true,
    price: 24.99,
  },
  {
    name: "GraphQL - The Complete Guide",
    author: "Stephen Grider",
    tags: ["Backend", "API", "GraphQL"],
    isPublished: true,
    price: 17.5,
  },
  {
    name: "HTML & CSS - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Frontend", "HTML", "CSS"],
    isPublished: true,
    price: 14.99,
  },
  {
    name: "Express.js - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Backend", "JavaScript", "Framework"],
    isPublished: true,
    price: 16.99,
  },
  {
    name: "PostgreSQL - The Complete Developer's Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Database", "SQL"],
    isPublished: true,
    price: 13.99,
  },
  {
    name: "React Native - The Complete Guide",
    author: "Adam Smith",
    tags: ["Mobile", "JavaScript", "Framework"],
    isPublished: true,
    price: 29.99,
  },
  {
    name: "Flask - The Complete Guide",
    author: "Jose Portilla",
    tags: ["Backend", "Python", "Framework"],
    isPublished: false,
    price: 21.99,
  },
  {
    name: "Svelte - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: true,
    price: 19.5,
  },
  {
    name: "Docker - The Complete Guide",
    author: "Stephen Grider",
    tags: ["DevOps", "Containerization", "Backend"],
    isPublished: true,
    price: 23.99,
  },
  {
    name: "Kubernetes - The Complete Guide",
    author: "Stephen Grider",
    tags: ["DevOps", "Containerization", "Backend"],
    isPublished: true,
    price: 27.99,
  },
  {
    name: "AWS - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Cloud", "AWS", "Backend"],
    isPublished: true,
    price: 34.99,
  },
  {
    name: "Next.js - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: true,
    price: 26.99,
  },
  {
    name: "Redis - The Complete Developer's Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Database", "NoSQL"],
    isPublished: true,
    price: 11.99,
  },
  {
    name: "Git - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Version Control", "DevOps", "Git"],
    isPublished: true,
    price: 9.99,
  },
  {
    name: "Java - The Complete Guide",
    author: "Jose Portilla",
    tags: ["Backend", "Java", "Programming"],
    isPublished: true,
    price: 28.99,
  },
  {
    name: "Spring Boot - The Complete Guide",
    author: "Adam Smith",
    tags: ["Backend", "Java", "Framework"],
    isPublished: true,
    price: 31.99,
  },
  {
    name: "C# - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Backend", "C#", "Programming"],
    isPublished: true,
    price: 22.99,
  },
  {
    name: ".NET Core - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Backend", "C#", "Framework"],
    isPublished: true,
    price: 24.5,
  },
  {
    name: "PHP - The Complete Guide",
    author: "Jose Portilla",
    tags: ["Backend", "PHP", "Programming"],
    isPublished: true,
    price: 18.5,
  },
  {
    name: "Laravel - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Backend", "PHP", "Framework"],
    isPublished: true,
    price: 20.99,
  },
  {
    name: "Ruby on Rails - The Spring Boot - The Complete Guide",
    author: "Adam Smith",
    tags: ["Backend", "Ruby", "Framework"],
    isPublished: false,
    price: 25.5,
  },
  {
    name: "Go - The Complete Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Go", "Programming"],
    isPublished: true,
    price: 21.5,
  },
  {
    name: "Rust - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Backend", "Rust", "Programming"],
    isPublished: true,
    price: 29.5,
  },
  {
    name: "React Hooks - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "JavaScript", "React"],
    isPublished: true,
    price: 16.5,
  },
  {
    name: "Vuex - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Frontend", "JavaScript", "State Management"],
    isPublished: true,
    price: 17.99,
  },
  {
    name: "Redux - The Complete Guide",
    author: "Stephen Grider",
    tags: ["Frontend", "JavaScript", "State Management"],
    isPublished: true,
    price: 19.99,
  },
  {
    name: "SASS - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Frontend", "CSS", "SASS"],
    isPublished: true,
    price: 13.5,
  },
  {
    name: "Bootstrap - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "CSS", "Framework"],
    isPublished: true,
    price: 14.5,
  },
  {
    name: "Tailwind CSS - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Frontend", "CSS", "Framework"],
    isPublished: true,
    price: 15.99,
  },
  {
    name: "Jenkins - The Complete Guide",
    author: "Stephen Grider",
    tags: ["DevOps", "CI/CD", "Automation"],
    isPublished: true,
    price: 26.5,
  },
  {
    name: "Terraform - The Complete Guide",
    author: "Jose Portilla",
    tags: ["DevOps", "Infrastructure", "Automation"],
    isPublished: true,
    price: 27.5,
  },
  {
    name: "Ansible - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["DevOps", "Automation", "Infrastructure"],
    isPublished: true,
    price: 28.5,
  },
  {
    name: "MySQL - The Complete Developer's Guide",
    author: "Stephen Grider",
    tags: ["Backend", "Database", "SQL"],
    isPublished: true,
    price: 12.5,
  },
  {
    name: "Elasticsearch - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Backend", "Database", "Search"],
    isPublished: true,
    price: 23.5,
  },
  {
    name: "Firebase - The Complete Guide",
    author: "Adam Smith",
    tags: ["Backend", "Cloud", "Firebase"],
    isPublished: true,
    price: 24.99,
  },
  {
    name: "Gatsby - The Complete Guide",
    author: "Maximilian Schwarzmüller",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: true,
    price: 22.99,
  },
  {
    name: "Nuxt.js - The Complete Guide",
    author: "Jonas Schmedtmann",
    tags: ["Frontend", "JavaScript", "Framework"],
    isPublished: true,
    price: 21.99,
  },
  {
    name: "Webpack - The Complete Guide",
    author: "Stephen Grider",
    tags: ["Frontend", "JavaScript", "Bundler"],
    isPublished: true,
    price: 18.99,
  },
  {
    name: "D3.js - The Complete Guide",
    author: "Adam Smith",
    tags: ["Frontend", "JavaScript", "Data Visualization"],
    isPublished: true,
    price: 20.5,
  },
  {
    name: "Machine Learning with Python",
    author: "Jose Portilla",
    tags: ["AI", "Python", "Machine Learning"],
    isPublished: true,
    price: 34.99,
  },
  {
    name: "Blockchain - The Complete Guide",
    author: "Stephen Grider",
    tags: ["Blockchain", "Cryptocurrency", "Backend"],
    isPublished: true,
    price: 29.99,
  },
];

module.exports = courses;
